### ISSUE TITLE
pnpm after 2.14.4 is not installed correctly

### ISSUE THREAD

**Issue by etamponi** [pnpm/self-installer#5]
This is the error I get when using pnpm installed with this installer, with any pnpm version after 2.14.4:

```
TypeError: write_json_file_1.default is not a function
    at /opt/pnpm/lib/node_modules/pnpm/lib/node_modules/@pnpm/package-requester/lib/packageRequester.js:311:52
    at Generator.next (<anonymous>)
    at fulfilled (/opt/pnpm/lib/node_modules/pnpm/lib/node_modules/@pnpm/package-requester/lib/packageRequester.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
```

**Comment by zkochan** [comment]
I don't know how that could happen. This package is published as a bundled file and pnpm is bundled with its dependencies
